"""Add columns to Artist

Revision ID: 33c503931b8d
Revises: 513ad9a03509
Create Date: 2020-08-25 20:55:56.183046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c503931b8d'
down_revision = '513ad9a03509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues_msg', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'url')
    op.drop_column('Artist', 'seeking_venues_msg')
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###
