"""Add columns to Venue

Revision ID: 513ad9a03509
Revises: ba98c6396b6b
Create Date: 2020-08-25 20:51:53.852033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513ad9a03509'
down_revision = 'ba98c6396b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent_msg', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'url')
    op.drop_column('Venue', 'seeking_talent_msg')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
